linters-settings:
  dupl:
    threshold: 100

  funlen:
    lines: 100
    statements: 50

  goconst:
    min-len: 2
    min-occurrences: 2

  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

  gocyclo:
    min-complexity: 15

  goimports:
    local-prefixes: github.com/CathalMullan/barb

  golint:
    min-confidence: 0

  gomnd:
    settings:
      mnd:
        checks: analyses, arguments, assigns, cases, conditions, operations, return

  govet:
    check-shadowing: true

  lll:
    line-length: 120

  maligned:
    suggest-new: true

  misspell:
    locale: US

  godox:
    keywords:
      - BUG
      - FIXME

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - misspell
    - nakedret
    - rowserrcheck
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - gochecknoglobals
    - gocognit
    - godox
    - maligned
    - prealloc
