project_name: barb

env:
  - GO111MODULE=on

builds:
  - main: ./cmd/barb/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - 386
    ldflags:
      - -s -w -X github.com/CathalMullan/barb/pkg/version.Version={{.Version}}

checksum:
  name_template: '{{ .ProjectName }}-checksums.txt'
  algorithm: sha256

changelog:
  sort: asc
